export const FETCH_IMAGES_TRIGGER = 'FETCH_IMAGES_TRIGGER';

export const FETCH_IMAGES_REQUEST = 'FETCH_IMAGES_START';

export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';

export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE';
